### ISSUE TITLE
SSP not working

### ISSUE THREAD

**Issue by mrdeadlocked** [DoubleDoorDevelopment/ItemBlacklist#1]
I loaded this mod up in SSP. Grabbed a BC Quarry types /blockitem ban. I switched dimensions and came back to overworld and I could still place down the quarry. When does the mod trigger  item creation?

**Comment by Claycorp** [comment]
The mod triggers on pickup, interaction and dimension switching.
Also it doesn't work in SSP as it was overlooked because it was built for a server.

**Comment by mrdeadlocked** [comment]
Ah alright. I was just testing it in SSP before I moved it over to SMP. :-) i'll just plop it on my server later. Sorry about this issue.

**Comment by dries007** [comment]
It needs to be fixed for SSP. Be sure to get the very latest build (1.0.0 fixed) or you'll crash on any non-standard rendering items.

**Comment by dries007** [comment]
Does not work in SSP since it thinks you are OP'ed. Will be fixed in next curse forge build.
