### ISSUE TITLE
Global item ban

### ISSUE THREAD

**Issue by tenten8401** [DoubleDoorDevelopment/ItemBlacklist#12]
Why allow players to just go into the nether or a personal made dimension to bypass blacklisted items? We need a global item ban feature.

**Comment by dries007** [comment]
Use `__GLOBAL__`, it should be in the tab complete list of the command, see example in readme if you are doing json.

**Comment by tenten8401** [comment]
Ah, thanks. Was trying *

**Comment by dries007** [comment]
You can also use ranges or multiple dimentions per list if you are editing the json, I don't think I ever added that to the command, see readme.

**Comment by tenten8401** [comment]
The command doesn't work for global, probably just going to have to use JSON.

**Comment by tenten8401** [comment]
Possibly re-open until global is a cmd?

**Comment by dries007** [comment]
Did you use the double underscore? It got turned into markdown above. `__GLOBAL__`

**Comment by Claycorp** [comment]
`__GLOBAL__` is a variable not a command so if you do `/blockitem ban __GLOBAL__` it works fine.

**Comment by tenten8401** [comment]
I was just about to say, I looked in the json and saw _ _ GLOBAL _ _, it works in the CMD. Thanks for the help. :+1:
