### ISSUE TITLE
REQUEST - ItemWhitelist

### ISSUE THREAD

**Issue by dillasyx** [DoubleDoorDevelopment/ItemBlacklist#13]
Is it possible, to make a whitelist? because i have 2 blocks, that should only be used in 3 of 40 dimensions and with blacklist, i have some problems, because of the many dimensions.

**Comment by Claycorp** [comment]
Mod already supports multiple DIM sets, Just set up the rule. https://github.com/DoubleDoorDevelopment/ItemBlacklist#ranges--multiple-dimensions
