### ISSUE TITLE
Banned items are global, even when specified otherwise?

### ISSUE THREAD

**Issue by Galadriel1640** [DoubleDoorDevelopment/ItemBlacklist#15]
Hey I don't know if I'm just doing this wrong or what, but I want to ban an item in just the overwolrd, which I am pretty sure is Dimension 0.  So I use the command /blockitem ban 0, while holding an item (the item ID isn't recognized by the mod for some reason) and it successfully bans the item; however, if I go to another dimension like The Deep Dark or The Nether or anything, the item is still banned.  Any clue whats going on? I've tried several items as well.

**Comment by Claycorp** [comment]
Can you get the Blacklist.JSON out of the world and post it here? Drag and drop it in or post on a text hosting site please!

**Comment by Galadriel1640** [comment]
Could I just post it like this since I just deleted it and added one item to test?
```
{
  "__GLOBAL__": [],
  "0": [
    {
      "item": "ExtraUtilities:enderQuarry",
      "damage": "*"
    }
  ]
}
```

**Comment by Galadriel1640** [comment]
I can still use pastbin or something if that makes a difference?
https://pastebin.com/hZmkqFih

**Comment by Claycorp** [comment]
This works, Its easier to read when posted somewhere else as markdown can make a mess of it.
What version of the mod are you using by chance?

**Comment by Galadriel1640** [comment]
Makes sense! We are running 1.7.10-1.2.0.8

**Comment by Claycorp** [comment]
Ooooh geez, 1.7.10.... Give me a bit to get something thrown together to test with. Last time I recall working with it things worked fine but that was some time ago... I also might have only been using global bans too.

**Comment by Galadriel1640** [comment]
Ah sorry about that, I honestly thought this was just me not understanding something xD

**Comment by Claycorp** [comment]
Seems to work fine beyond the lock item showing up backwards when switching DIMs.... Not sure whats up with that.

Try placing the items in the DIMs they are allowed VS banned. I tested in single player that's all FYI.

**Comment by Galadriel1640** [comment]
I've tried placing them but the only way it works is if I spawn in a new item, but it will work even in banned worlds if I do that.  I've also tried transferring it between players and that doesn't seem to work either.  Could just be a server issue then?

**Comment by Claycorp** [comment]
It might be. I didn't spin up a server to test with as we are moving off 1.7.10 - 1.10.2, Especially sense we started moving things to 1.12 just recently.

I'll leave this open and see what @dries007 thinks as its up to him to get it fixed or not. I couldn't reproduce it in single player though.

**Comment by Galadriel1640** [comment]
I understand, only reason we are sticking to 1.7.10 is due to some mods never getting updated past here.  Thanks so much for trying!

**Comment by Claycorp** [comment]
TBH if its a small fix he is fairly nice about doing so. Keep an eye on this as it will be the first thing he looks at tomorrow.

**Comment by dries007** [comment]
First: OPs bypass the restriction.
If that's not it, try moving the json file from the config to the world folder (or vice versa).
I can't reproduce this issue on a 'vanilla' server. (I used wool and the nether and it worked.)

**Comment by Galadriel1640** [comment]
I actually am unable to bypass it while opped, oddly enough, but I tested both to make sure. I'll move the JSON file to the config folder tonight and report back!

**Comment by Galadriel1640** [comment]
Looks like that didn't work, so I guess it's just something on my server breaking it >.< thanks for your time!

**Comment by dries007** [comment]
Mind trying with a 'vanilla' server with only ExtraUtilities on it?

2017-08-03 0:15 GMT+02:00 Galadriel1640 <notifications@github.com>:

> Looks like that didn't work, so I guess it's just something on my server
> breaking it >.< thanks for your time!
>
> Sent from my iPhone
>
