### ISSUE TITLE
Item Blacklist & Mod Packs (Question)

### ISSUE THREAD

**Issue by Winddbourne** [DoubleDoorDevelopment/ItemBlacklist#16]
I just downloaded item blacklist for use in my mod pack  . . . I wanted to give different dimensions their own flavor based on what could be used in each one. However the configuration file doesn't seem to hold the list of blocked items and you mentioned the JSON being in the save file in a previous issue . . .

So my question is how do I package the block list so that it can be downloaded and used as a default for every world that uses my pack?

**Comment by Claycorp** [comment]
You need to copy the JSON from the world you blacklisted all the items in to the config folder.

For more info on how it all works its documented here https://github.com/DoubleDoorDevelopment/ItemBlacklist#pack-vs-world-bans
