### ISSUE TITLE
Please push this to 1.12.2 - Forge 90 I found quite a few too many op items.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DoubleDoorDevelopment/ItemBlacklist#17]

**Comment by TheQKnight** [comment]
I would like it to be ported as well. I have no knowledge of modding so I wouldn't be much help.

**Comment by Claycorp** [comment]
@TheQKnight We get that you want an update, You don't need to ask three times about it. There are no plans for an update but anyone that is capable has the resources to do it. The answer isn't going to change and you where told this already.
