### ISSUE TITLE
Feature Suggestion: UnWrenchable Blocks.

### ISSUE THREAD

**Issue by K4N0** [DoubleDoorDevelopment/ItemBlacklist#2]
I'm Really loving your mod. This is perfectly what i needed to protect my spawn world.
Specially from Flan's mod that players were able to shoot glass in a protected spawn area.
Thank you so much!.

Suggestion: I have an issue with blocks that can be wrenched at spawn.
more specifically Thermal Expansion, Ender Io, Matter Overdrive ect.

Any way to make it so that blocks in that dimension can't be interacted with.
I wanted to make a Tutorial on how to build such things at spawn, or how to set up certain machines, but i'm unable to. Players can just wrench the machines and run off with them.

**Comment by Claycorp** [comment]
Thanks! Glad that people are getting use out of it.
You forgot the suggestion part :P Not sure what you mean by "unwrenchable blocks"....

**Comment by K4N0** [comment]
sorry, i just updated it, i accidently clicked the done button

**Comment by K4N0** [comment]
I'll make a quick mod showcase once you feel you've added enough content to it, or i can just make one now.
This is my latest mod showcase.
https://www.youtube.com/watch?v=ZPpi0PKEkRQ

**Comment by Claycorp** [comment]
If you ban all the wrenches in that dimension you should be fine. If you are looking for a way to ban them only in that area this won't work and likely never will be added. That makes stuff super complicated. Wrench or not to wrench is the question!

**Comment by Claycorp** [comment]
If you want to do a showcase feel free. Currently the mod doesn't work for SSP but it will be fixed someday.

**Comment by K4N0** [comment]
Good idea on the wrench banning.
Server spawn is in it's own dimension/world.
I wasn't looking for a certain area.
I Think it will be fine if i just ban the wrenches.
I have a Server for my modpack that runs 24/7
I also have a test server for testing out mods and such before i add to the real server.
Anything special you want to let youtubers know about?
Credits? Shout outs? Information?

**Comment by Claycorp** [comment]
All the info should be on curse. http://minecraft.curseforge.com/projects/item-blacklist?gameCategorySlug=mc-mods&projectID=237226

**Comment by K4N0** [comment]
What does unpack and pack do?

**Comment by Claycorp** [comment]
The way the mod works is it puts the banned item inside a 'container item' So its technically an item inside an item. Pack and unpack puts/removes the items into/from the container so Op's can still use banned items.

**Comment by K4N0** [comment]
nice!!

**Comment by Claycorp** [comment]
I'm going to close this as you know what you want to do and such. If ya need anything else go ahead and make a new issue.

**Comment by K4N0** [comment]
It works really great with the few items i've tried. I'm just going to ban everything, well, everything i think  will cause a issue on the spawn world, it's not like they need it. Thanks again for such an epic mod.

**Comment by Claycorp** [comment]
Not a problem. @dries007 Does good work :+1:
