### ISSUE TITLE
Permissions on commands

### ISSUE THREAD

**Issue by Husky110** [DoubleDoorDevelopment/ItemBlacklist#22]
Heyho,

What permission do I need in luckyperms or PEX to run the blockitem-commands?
This is nowhere documented...

**Comment by dries007** [comment]
None, because this is a forge mod and thus has no support for any Bukkit permssion api.
That's also why it's not documented. Because it doesn't exist.

**Comment by Husky110** [comment]
So basicly this aspect is BS (pardon my french), since as soon as you install luckyperms (which starts to become standard) you are not allowed to run the blockitem-command... you should consider an update here...

**Comment by dries007** [comment]
Guess who's fault is that? OH: It's Luckyperms who interferes with standard Forge/Minecraft operations.
They are responsible for the permissions, so they should document what permissions "normal" (non bukkit) commands get by default.

**Comment by Husky110** [comment]
Funny, cause almost all forge-plugins I use come with some sort of permissions which can then be hooked by luckyperms or pex.

**Comment by dries007** [comment]
I assume you mean mods, because forge plugins don't exist. But I guess you are lucky then, because I haven't seen many of those around. Feel free to provide a link so we can have a look and see how they do it.

**Comment by Husky110** [comment]
https://minecraft.curseforge.com/projects/denyblocks

**Comment by dries007** [comment]
Use this to see what permission it's checking for: https://github.com/lucko/LuckPerms/wiki/Verbose
I'm assuming luckyperms here but I'm assuming PEX has something similar.
Feel free to share your findings to we can point people here in the future.

**Comment by Husky110** [comment]
okay.
The permission in use is: itemblacklist.command.blockitem
Using itemblacklist.command.* unlocks all commands on a user or a group.
Maybe add this to the docs/description.

**Comment by dries007** [comment]
Alright, that makes sense, it's `<modid>.command.<commandname>`.
I couldn't quickly find that documented on their wiki/FAQ/google. 
@Claycorp Can you add this to our readmes & CF pages (maybe include a link to the verbose thing) wherever people have been asking.

**Comment by Claycorp** [comment]
Yeah, I'll update the page with the link.
Though.... people still should know how to use the things they install and not rely on 3rd parties to point them to stuff they don't control. After all this is a forge mod, not a whatever they call bukkit+forge servers these days.

**Comment by Husky110** [comment]
Sponge...
