### ISSUE TITLE
Packed items not rendering

### ISSUE THREAD

**Issue by mrdeadlocked** [DoubleDoorDevelopment/ItemBlacklist#3]
![2015-10-28_22-48-45](https://cloud.githubusercontent.com/assets/461352/10808842/4bba1bf4-7dc6-11e5-8805-ea08b6dd1807.png)
![2015-10-28_22-48-31](https://cloud.githubusercontent.com/assets/461352/10808844/4bbc889e-7dc6-11e5-81c5-3d5c900c1c26.png)
![2015-10-28_22-48-02](https://cloud.githubusercontent.com/assets/461352/10808843/4bbc370e-7dc6-11e5-94ad-bf3cf8179e12.png)

The above is rendered when I set the digital miner as a blockeditem and it gets packed.

**Comment by Claycorp** [comment]
@dries007 will need to look into this. I know nothing about how the rendering works or if it has any safety checks for problem renders.

**Comment by dries007** [comment]
Are you sure you have the latest build?
(Also, what mod is that from, so I can check to see what its doing)

**Comment by mrdeadlocked** [comment]
Digital Miner from mekanism. We are using the  version thats on curse.

**Comment by dries007** [comment]
Has since been fixed I'm pretty sure. Reopen if not. (Build on curse will be updated later)
