### ISSUE TITLE
[Suggestion] Please Add Ban Item from Hand

### ISSUE THREAD

**Issue by Silverrain2004** [DoubleDoorDevelopment/ItemBlacklist#32]
That would be useful. A command that bans / blocks item in your Hand. 

Something like /blockitem ban __GLOBAL__ hand

That would be very useful.

**Comment by Claycorp** [comment]
It already does and has forever?

> - ban [dim list] [item[:*:meta]] - Bans the item. (Defaults to the item you are holding and the dimension you are in.)
> - unban [item[:*:meta]] - Unbans the item. (Defaults to the item you are holding and the dimension you are in.)

Thus if you do `/blockitem ban __GLOBAL__` whatever you are holding will be banned. Including all subsets of that item. If you want a meta specific ban you need to type it.
