### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by Arthurtheking98** [DoubleDoorDevelopment/ItemBlacklist#33]
Hello, guys. I'm not into technical stuff much, please, can you explain to me how to use the mod on the following example :

I want to ban item called Soulstone Empty in Custom Npcs mod.

F3 of the item :

![2019-12-03_07 53 01](https://user-images.githubusercontent.com/57798726/70025436-be9d7a00-15a5-11ea-8040-4804ebf05ff0.png)

error I get each time I'm using /ban command :

![2019-12-03_07 54 02](https://user-images.githubusercontent.com/57798726/70025438-be9d7a00-15a5-11ea-855f-ed7b2c2e9f9c.png)

I tried giving command in lots of different ways, however, non seems to work and give the error from the above :

![2019-12-03_07 56 09](https://user-images.githubusercontent.com/57798726/70025434-be04e380-15a5-11ea-8fb2-fa01d8dd63a7.png)

minecraft 1.11.2

I browsed everything I could to find more explanation how to do it, but I did not find anything more than basic instructions, written to the mod om every minecraft website.

Thank you.

**Comment by Claycorp** [comment]
All the info you need is on the CurseForge project.
https://www.curseforge.com/minecraft/mc-mods/item-blacklist

`/ban` isn't a valid command as ban is a sub command of `/blockitem` as mentioned on the CF project and in your screenshot. `/blockitem ban` is what you would be using instead.
Also that would overlap with the server ban....
