### ISSUE TITLE
Commandblock output said you DO NOT HAVE PERMISSION TO USE THIS COMMAND

### ISSUE THREAD

**Issue by emthy0** [DoubleDoorDevelopment/ItemBlacklist#34]

**Comment by Claycorp** [comment]
I have no idea what you are doing or want me to fix.
Provide more information like what command your trying to use, what your goal is to do whatever it is you are doing.

**Comment by ChukiStrike** [comment]
@Claycorp permissions?

**Comment by Claycorp** [comment]
For what command?
Anyone can use `/unpack`, op level is 4 for `/blockitem`. There isn't any other perms for forge mods. If you add something that messes with them that's on you.

IDK what they are doing so I can help/fix it. It's been nearly 30 days without a reply so this is getting closed.
