### ISSUE TITLE
Pack and Blockitem dont work on Multiplayer

### ISSUE THREAD

**Issue by Silverrain2004** [DoubleDoorDevelopment/ItemBlacklist#35]
Hi there i am using latest ItemBlacklist. ItemBlacklist-1.4.3.

I have blocked some Items in Singleplayer via Pack-Command. There is written an output in Chat. And Item is blocked with Pack-Command. But i havent found any ItemBlacklist.json. If i ban Items on a Server, i get the Information. If i type List, i get the Items that i banned. But a normal Player can still interact with that item. And even me. I have tried with Op-Account, then i have tested it with my second Account (not Op just normal Player) and it was the same. I have taken my Pickaxe and mined that Resource, and i am able to use it.

**Comment by Claycorp** [comment]
It certainly does work on servers.
Either you are using something that breaks permissions or your not using a Forge server.

Item Blacklist saves the banned items in the world folder as mentioned on the CurseForge project page.

**Comment by Claycorp** [comment]
As there has been no follow up on this It's getting closed.
