### ISSUE TITLE
java.lang.IllegalArgumentException: Stack can not be invalid!

### ISSUE THREAD

**Issue by SSenZ0** [DoubleDoorDevelopment/ItemBlacklist#39]
### Description:
Server crashed upon opening a backpack from the Improved Backpacks mod with items that have been blacklisted/banned via the Item Blacklist mod

### To Reproduce:

Globally ban an item via the mod
put it in a backpack
open the backpack

### Expected behavior:
no crashes

### Additional information:

Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Mod version:1.4.3

I'm unsure on what exactly the problem is but i saw "itemblacklist" being mentioned in the crashreport, take a look.
[CrashReport](https://paste.gg/p/anonymous/f2447b51da8d4dc795659fb36f801521)

ALREADY REPORTED ON THE IMPROVED BACKPACKS GITHUB!!!

**Comment by Claycorp** [comment]
I don't particularly see how this could be a problem from our mod. The other mod doesn't have source so I'm not digging into this.
