### ISSUE TITLE
[Suggestion] A certain number of items.

### ISSUE THREAD

**Issue by Tsyklop** [DoubleDoorDevelopment/ItemBlacklist#6]
The idea is as follows. Add the ability to limit the number of uses of the block. meaning that, in the configuration or command is given for the number of performances taken block - Block will be to craft many times, but put only as much as you specified in the config file.

**Comment by Claycorp** [comment]
This isn't the type of mod for that. The this idea works is a total opposite of how the mod works. It makes items unuseable by anything/everyone equally. There is no tracking of who can use items, how many times they can be used or anything beyond making sure that the item isn't useable.

This will not be done as it would require a total overhaul of the mod to store all the extra info and make it work the way you ask.

**Comment by Tsyklop** [comment]
@Claycorp I can throw a code of implementation.

**Comment by Claycorp** [comment]
Your sentence doesn't make sense in english. Just FYI.

Yeah if you can make it work and submit a PR it can be looked over. Theres no guarantee it will get added though.
