### ISSUE TITLE
[Feature Request] Modpack disabled items

### ISSUE THREAD

**Issue by Cazadorsniper** [DoubleDoorDevelopment/ItemBlacklist#7]
Is it possible to have items banned through the modpack itself anytime a new world is created?

**Comment by dries007** [comment]
Sure, That should be doable.

**Comment by Cazadorsniper** [comment]
yes, thank you :)

**Comment by dries007** [comment]
I think the following implementation would be the best:
If there is a file in the config directory, copy that over to the world one.
- The advantage is that its easily editable per world/server, 
- The disadvantage is that it would not be overwritten after pack updates.

Would this be acceptable or do you need it to update on pack updates?

**Comment by Cazadorsniper** [comment]
I think I need it to update on pack updates, I just need it to blacklist items that will stay blacklisted on new worlds no matter the world type.

**Comment by dries007** [comment]
OK, that will take some more effort.

**Comment by dries007** [comment]
You should test the latest version: https://jenkins.dries007.net/job/ItemBlacklist/

**Comment by Cazadorsniper** [comment]
how do i get it to work? >.>

**Comment by Claycorp** [comment]
This is a shot in the dark but try banning things you wish to ban and then copy the JSON file out of the world and place it in the config folder.
You can ban items in all dims with `/blockitem ban __GLOBAL__` That will ban whatever item you are currently holding everywhere. [Curseforge ](http://minecraft.curseforge.com/projects/item-blacklist) will have full command documentation.

If this doesn't work you will need to wait for dries tomorrow as I have no way to test anything with a broken computer. I just took an educated guess after looking at some of the changes.

**Comment by Cazadorsniper** [comment]
I can't even find the json file and the message ingame is invisible when you ban an item

**Comment by dries007** [comment]
The file appears (after an item gets banned) inside the World's save folder.

Just a wild guess, but do you happen to have set your Game to anything but
english?

Also, Yes. The way to do it is to make a file in the world (using command)
and then putting it into the config dir.

**Comment by Cazadorsniper** [comment]
no its all english and only found banneditems.cfg in the worlds save folder but only contains something to do about the commandblock and nothing else

**Comment by dries007** [comment]
It should be called "ItemBlacklist.json"

**Comment by Cazadorsniper** [comment]
when i search for it only shows the .jar in the mods folder and .cfg in the configs folder.

**Comment by dries007** [comment]
Did you ban van item? I don't think it makes the file if it's empty.

**Comment by dries007** [comment]
So it turns out I'm stupid and may have forgotten to test some stuff, I'll let you know when you can try again.

**Comment by Claycorp** [comment]
GG dries... GG...

**Comment by dries007** [comment]
@Cazadorsniper Please try the latest build from jenkins, if it works, it's going up to Curse.

**Comment by Cazadorsniper** [comment]
it works :) thank you so much

**Comment by dries007** [comment]
I just pushed it to curse, so it should appear within a couple of hours.
