### ISSUE TITLE
Crash when using an Ender Pouch from ChickenBones' Ender Storage

### ISSUE THREAD

**Issue by Xandermud** [DoubleDoorDevelopment/ItemBlacklist#8]
Title basically says it. When trying to use an ender pouch that has been banned the client crashes.

Crash Report:
http://pastebin.com/D025JaeW

**Comment by dries007** [comment]
OK, I'm working on this. I think it may be some magic ChickenBones does causing issues. I'll do my very best to fix it, if that happens to be impossible, I think I may add a way to prevent items from doing the fancy render trick. (they will just render a specific error icon, better then crashing)

**Comment by Xandermud** [comment]
That was fast. Thank you very much =)

**Comment by dries007** [comment]
It helped that I had a rough idea of where to look :smile: The build is up on curseforge too.
