### ISSUE TITLE
Not compatible with 1.10.2?

### ISSUE THREAD

**Issue by Nullga** [DoubleDoorDevelopment/ItemBlacklist#9]
I'm on Forge 1.10.2-2-.18.1.2011 to run item blacklist however it crashes. when launching.

http://pastebin.com/siSBxJRJ

**Comment by dries007** [comment]
It seems the event got removed and replaced because of the Forge re-licensing. It has been removed for now, until when we separate the 1.10 build. It won't change much of the functionality. Will push to curse ASAP.
